### ISSUE TITLE
[Bug] Unable to open $file

### ISSUE THREAD

**Issue by Kristinita** [fwph/codepresenter#4]
### Summary

I can not begin to use Code Presenter.

### Expected behavior

Successful code presentation.

### Actual behavior

Blank files open for me.

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

In `E:\Киролайна` directory of my sidebar I create folders `SourceFolder` and `SinkFolder`. I add in `SourceFolder` folder 2 files: [hangman.py](https://gist.github.com/f68df0b1937ff40cb2044c63315c28a1) and [tic-tac-toe.py](https://gist.github.com/5b88c614886c5a438a153b34330cd892). I set folders in sidebar:

    command: code_presenter_set_sink {"dirs": ["E:\\Киролайна\\SinkFolder"]}
    command: code_presenter_set_source {"dirs": ["E:\\Киролайна\\SourceFolder"]}

<kbd>Ctrl+Shift+P</kbd> → `Code Presenter: Start Code Presentation` → all open tabs was closed for me and 2 blank file `SinkFolder\hangman.py` and `SinkFolder\tic-tac-toe.py` open for me.

```
command: code_presenter_activate
Unable to open /E/Киролайна/SinkFolder/tic-tac-toe.py
Unable to open /E/Киролайна/SinkFolder/hangman.py
```

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by fwph** [comment]
Thanks for the report. I'll boot up my windows side to check the latest build there (I cannot reproduce the problem on OSX), but just to confirm, the two file windows open in sublime text, but when you type characters, the contents of `SourceFolder/tic-tac-toe.py` and `SourceFolder/hangman.py` are not displayed?

Also, to rule this out, could you try this with a top-level folder that is ASCII characters only(eg, `e:\codepresenter-test`). CodePresenter does not manipulate the encoding of the paths at all, but there could be an interaction, though I'd _hope_ at this point that windows system locale is treated as utf-\* everywhere.

**Comment by fwph** [comment]
Okay, so having booted into windows, what I'm seeing is that while windows complains in the terminal `Unable to open file`, this does not indicate a failure: just that the file does not exist yet (which is okay -- just a difference from what OSX/Linux do). On my windows 10 install, with 32 bit ST3 build 3126, the message appears, but the blank files correctly open.

You can expect that the files will be blank when initially loading, but when you type (or just repeatedly press the same button), the contents of the file should appear. For the files to not be blank, you'll need to set a 'fast forward point' at some location in the file from which you want to begin typing (anything before the fast forward point will be added to the file before the presentation begins, and when typing in that file's sink buffer, whatever is past that point will show).

If this behavior is not what you are seeing, then we'll need to dig deeper.

**Comment by Kristinita** [comment]
At first I don't understand, that in opened files I need press any key in keyboard.

Thank you!
