### ISSUE TITLE
[Bug] Incorrect Cyrillic symbols presentation

### ISSUE THREAD

**Issue by Kristinita** [fwph/codepresenter#5]
### Summary

Cyrillic symbols print not correct for me.

### Expected behavior

Correct Cyrillic symbols presentation.

### Actual behavior

![Actual](http://i.imgur.com/FlNoWjf.gif)

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I make source and sync folders like [this topic](https://github.com/fwph/codepresenter/issues/4#issue-189930534). In source folder I create `Sasha.md` file, its content:

    Не принять мне итоги, чья щемит прямота. Отречений дороги заведут в никуда.
    Ты — цветок Поднебесья, Ты — улыбка в ночи, эхо сладостных песен и Венеры лучи.
    Ты — колибри прекрасный, Амазонки сапфир, — дочь природы несчастной в звуках музыки лир.
    Личность мерно теряешь, изучая Тебя. Сон, еду забываешь, без сознанья Любя.

<kbd>Ctrl+Shift+P</kbd> → `CodePresenter: Start Code Presentation` → in opened file I press any key in keyboard → I get actual behavior.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by fwph** [comment]
This one is going to be a bit trickier, it looks like ST's python interpreter is not respecting the OS encoding defaults and is having trouble figuring out what they are. I suspect the first step is forcing it to treating files as UTF-8 encoding, which at least is a start.

**Comment by fwph** [comment]
I've released version 1.2.0 now; once this gets through package install, it should handle this problem. Note that it will require that your files are UTF-8 encoded, but that looks like it is the case here.

**Comment by fwph** [comment]
(let me know if this improves)

**Comment by Kristinita** [comment]
@fwph, thanks, it's work!
